import secrets

from fastapi import FastAPI, Query
from fastapi.responses import HTMLResponse

import httpx
from jinja2 import Template
from cryptography.fernet import Fernet

app = FastAPI(title="FastAPI App", version="1.0.0")


@app.get("/")
def hello():
    return {"message": "Hello, World!"}


@app.get("/crypto/encrypt")
def crypto_encrypt(message: str = Query("Hello, World!", max_length=1000)):
    """Encrypt a message using Fernet symmetric encryption."""
    key = Fernet.generate_key()
    f = Fernet(key)
    encrypted = f.encrypt(message.encode())
    decrypted = f.decrypt(encrypted).decode()
    return {
        "original": message,
        "key": key.decode(),
        "encrypted": encrypted.decode(),
        "decrypted": decrypted,
        "verified": decrypted == message,
    }


@app.get("/template/render", response_class=HTMLResponse)
def template_render(
    name: str = Query("World"),
    items: int = Query(5, ge=1, le=20),
):
    """Render an HTML template using Jinja2."""
    tmpl = Template(
        """
    <!DOCTYPE html>
    <html>
    <head><title>Hello {{ name }}</title></head>
    <body>
        <h1>Hello, {{ name }}!</h1>
        <p>Here are {{ items|length }} random items:</p>
        <ul>
        {% for item in items %}
            <li>Item #{{ loop.index }}: {{ item }}</li>
        {% endfor %}
        </ul>
        <footer>Generated by FastAPI + Jinja2</footer>
    </body>
    </html>
    """
    )
    random_items = [f"Value-{secrets.token_hex(4)}" for _ in range(items)]
    html = tmpl.render(name=name, items=random_items)
    return HTMLResponse(content=html)


@app.get("/healthcheck")
def healthcheck():
    """Test each real dependency with a basic operation."""
    results = {}

    # --- fastapi ---
    try:
        import fastapi as _fa

        results["fastapi"] = {"status": "ok", "version": _fa.__version__}
    except Exception as e:
        results["fastapi"] = {"status": "error", "error": str(e)}

    # --- httpx ---
    try:
        import httpx as _hx

        client = _hx.Client()
        client.close()
        results["httpx"] = {"status": "ok", "version": _hx.__version__}
    except Exception as e:
        results["httpx"] = {"status": "error", "error": str(e)}

    # --- jinja2 ---
    try:
        from jinja2 import Template as J2Template

        rendered = J2Template("Hello {{ name }}").render(name="healthcheck")
        results["jinja2"] = {"status": "ok", "rendered": rendered}
    except Exception as e:
        results["jinja2"] = {"status": "error", "error": str(e)}

    # --- cryptography ---
    try:
        from cryptography.fernet import Fernet as F

        key = F.generate_key()
        f = F(key)
        ct = f.encrypt(b"healthcheck")
        pt = f.decrypt(ct)
        results["cryptography"] = {
            "status": "ok",
            "detail": f"encrypt/decrypt verified: {pt == b'healthcheck'}",
        }
    except Exception as e:
        results["cryptography"] = {"status": "error", "error": str(e)}

    # --- numpy ---
    try:
        import numpy as np

        results["numpy"] = {"status": "ok", "version": np.__version__}
    except Exception as e:
        results["numpy"] = {"status": "error", "error": str(e)}

    # --- onnxruntime ---
    try:
        import onnxruntime as ort

        results["onnxruntime"] = {"status": "ok", "version": ort.__version__}
    except Exception as e:
        results["onnxruntime"] = {"status": "error", "error": str(e)}

    # --- tokenizers ---
    try:
        from tokenizers import Tokenizer, models

        Tokenizer(models.BPE())
        results["tokenizers"] = {"status": "ok"}
    except Exception as e:
        results["tokenizers"] = {"status": "error", "error": str(e)}

    # Summary
    ok_count = sum(1 for r in results.values() if r["status"] == "ok")
    error_count = sum(1 for r in results.values() if r["status"] == "error")
    failed = [name for name, r in results.items() if r["status"] == "error"]

    return {
        "summary": {
            "total": len(results),
            "ok": ok_count,
            "errors": error_count,
            "failed_packages": failed,
        },
        "results": results,
    }
