import secrets
from typing import Optional

from fastapi import FastAPI, Query
from fastapi.responses import HTMLResponse

import httpx
from jinja2 import Template
from cryptography.fernet import Fernet

app = FastAPI(title="FastAPI App", version="1.0.0")


@app.get("/")
def hello():
    return {"message": "Hello, World!"}


@app.get("/crypto/encrypt")
def crypto_encrypt(message: str = Query("Hello, World!", max_length=1000)):
    """Encrypt a message using Fernet symmetric encryption."""
    key = Fernet.generate_key()
    f = Fernet(key)
    encrypted = f.encrypt(message.encode())
    decrypted = f.decrypt(encrypted).decode()
    return {
        "original": message,
        "key": key.decode(),
        "encrypted": encrypted.decode(),
        "decrypted": decrypted,
        "verified": decrypted == message,
    }


@app.get("/template/render", response_class=HTMLResponse)
def template_render(
    name: str = Query("World"),
    items: int = Query(5, ge=1, le=20),
):
    """Render an HTML template using Jinja2."""
    tmpl = Template(
        """
    <!DOCTYPE html>
    <html>
    <head><title>Hello {{ name }}</title></head>
    <body>
        <h1>Hello, {{ name }}!</h1>
        <p>Here are {{ items|length }} random items:</p>
        <ul>
        {% for item in items %}
            <li>Item #{{ loop.index }}: {{ item }}</li>
        {% endfor %}
        </ul>
        <footer>Generated by FastAPI + Jinja2</footer>
    </body>
    </html>
    """
    )
    random_items = [f"Value-{secrets.token_hex(4)}" for _ in range(items)]
    html = tmpl.render(name=name, items=random_items)
    return HTMLResponse(content=html)


@app.get("/health")
def health():
    """Health check with dependency versions."""
    import openai
    import litellm
    import tiktoken

    return {
        "status": "ok",
        "dependencies": {
            "openai": openai.__version__,
            "litellm": litellm.__version__,
            "tiktoken": tiktoken.__version__,
            "cryptography": "43.0.3",
            "fastapi": "0.115.14",
        },
    }
